"""
TOTP (Time-based One-Time Password) method implementation.
"""
import pyotp
import qrcode
import os
import tempfile
from typing import Dict, Any
from django.conf import settings
from .base import Base2FAMethod


class TOTPMethod(Base2FAMethod):
    """
    TOTP-based authentication using authenticator apps.
    """
    name = "totp"
    verbose_name = "Authenticator App (TOTP)"
    
    def send(self, user) -> bool:
        """
        TOTP doesn't send anything - codes are generated by the app.
        """
        return True
    
    def verify(self, user, token: str) -> bool:
        """
        Verify a TOTP token.
        """
        from nova2fa.models import UserTwoFactorSettings
        from nova2fa.encryption import decrypt_secret
        
        try:
            settings_obj = UserTwoFactorSettings.objects.get(user=user)
            
            # Check if account is locked
            if settings_obj.is_locked():
                return False
            
            if not settings_obj.totp_secret:
                return False
            
            # Decrypt the secret
            try:
                secret = decrypt_secret(settings_obj.totp_secret)
            except ValueError:
                # If decryption fails, might be legacy plain text
                secret = settings_obj.totp_secret
            
            totp = pyotp.TOTP(secret)
            is_valid = totp.verify(token)
            
            if is_valid:
                settings_obj.reset_failed_attempts()
            else:
                settings_obj.increment_failed_attempts()
            
            return is_valid
            
        except UserTwoFactorSettings.DoesNotExist:
            return False
    
    def setup(self, user) -> Dict[str, Any]:
        """
        Generate TOTP secret and QR code for setup.
        """
        from nova2fa.encryption import encrypt_secret
        
        # Generate secret
        secret = pyotp.random_base32()
        
        # Encrypt the secret for storage
        encrypted_secret = encrypt_secret(secret)
        
        # Get issuer name from settings
        issuer = getattr(settings, 'NOVA2FA_TOTP_ISSUER', 'Nova2FA')
        
        # Generate provisioning URI (use plain secret for QR code)
        totp_uri = pyotp.totp.TOTP(secret).provisioning_uri(
            name=user.email,
            issuer_name=issuer
        )
        
        # Generate QR code
        qr_code_path = self._generate_qr_code(totp_uri)
        
        return {
            'secret': encrypted_secret,  # Return encrypted for storage
            'secret_display': secret,     # Plain text for manual entry
            'qr_code_path': qr_code_path,
            'totp_uri': totp_uri
        }
    
    def _generate_qr_code(self, totp_uri: str) -> str:
        """
        Generate a QR code image for the TOTP URI.
        """
        qr = qrcode.QRCode(
            version=1,
            error_correction=qrcode.constants.ERROR_CORRECT_L,
            box_size=10,
            border=4,
        )
        qr.add_data(totp_uri)
        qr.make(fit=True)
        
        img = qr.make_image(fill_color="black", back_color="white")
        
        # Create a temporary file
        fd, filepath = tempfile.mkstemp(suffix='.png')
        os.close(fd)
        
        # Save the image
        img.save(filepath)
        
        return filepath
    
    def is_configured(self, user) -> bool:
        """
        Check if TOTP is configured for the user.
        """
        from nova2fa.models import UserTwoFactorSettings
        
        try:
            settings_obj = UserTwoFactorSettings.objects.get(user=user)
            return bool(settings_obj.totp_secret)
        except UserTwoFactorSettings.DoesNotExist:
            return False