"""
TOTP (Time-based One-Time Password) method implementation.
"""
import pyotp
import qrcode
import os
import tempfile
from django.conf import settings
from .base import Base2FAMethod


class TOTPMethod(Base2FAMethod):
    """
    TOTP-based authentication using authenticator apps.
    """
    name = "totp"
    verbose_name = "Authenticator App (TOTP)"
    
    def send(self, user):
        """
        TOTP doesn't send anything - codes are generated by the app.
        """
        return True
    
    def verify(self, user, token):
        """
        Verify a TOTP token.
        """
        from nova2fa.models import UserTwoFactorSettings
        
        try:
            settings_obj = UserTwoFactorSettings.objects.get(user=user)
            if not settings_obj.totp_secret:
                return False
            
            totp = pyotp.TOTP(settings_obj.totp_secret)
            return totp.verify(token)
        except UserTwoFactorSettings.DoesNotExist:
            return False
    
    def setup(self, user):
        """
        Generate TOTP secret and QR code for setup.
        """
        # Generate secret
        secret = pyotp.random_base32()
        
        # Get issuer name from settings
        issuer = getattr(settings, 'NOVA2FA_TOTP_ISSUER', 'Nova2FA')
        
        # Generate provisioning URI
        totp_uri = pyotp.totp.TOTP(secret).provisioning_uri(
            name=user.email,
            issuer_name=issuer
        )
        
        # Generate QR code
        qr_code_path = self._generate_qr_code(totp_uri)
        
        return {
            'secret': secret,
            'qr_code_path': qr_code_path,
            'totp_uri': totp_uri
        }
    
    def _generate_qr_code(self, totp_uri):
        """
        Generate a QR code image for the TOTP URI.
        """
        qr = qrcode.QRCode(
            version=1,
            error_correction=qrcode.constants.ERROR_CORRECT_L,
            box_size=10,
            border=4,
        )
        qr.add_data(totp_uri)
        qr.make(fit=True)
        
        img = qr.make_image(fill_color="black", back_color="white")
        
        # Create a temporary file
        fd, filepath = tempfile.mkstemp(suffix='.png')
        os.close(fd)
        
        # Save the image
        img.save(filepath)
        
        return filepath
    
    def is_configured(self, user):
        """
        Check if TOTP is configured for the user.
        """
        from nova2fa.models import UserTwoFactorSettings
        
        try:
            settings_obj = UserTwoFactorSettings.objects.get(user=user)
            return bool(settings_obj.totp_secret)
        except UserTwoFactorSettings.DoesNotExist:
            return False